version: '3'

services:
  golang:
    build: ./app/
    container_name: go_container
    ports:
      - 18080:8080
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: akiyadego
      MYSQL_USER: akiya
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    build: ./mysql/
    volumes:
       - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306

  ## Nginx
  # proxy:
  #   container_name: nginx_container
  #   build: ./nginx/
  #   ports:
  #     - 18082:80
  #   depends_on:
  #     - golang

