name: cicd

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md
      - .env
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DBNAME: ${{ secrets.DBNAME }}
  DBUSER: ${{ secrets.DBUSER }}
  DBPASS: ${{ secrets.DBPASS }}
  DBPROTOCOL: ${{ secrets.DBPROTOCOL }}
  LOGFILE: ${{ secrets.LOGFILE }}
  STATIC: ${{ secrets.STATIC }}
  AKIYAPASS: ${{ secrets.AKIYAPASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create dot env file
        run: |
          sh ./.github/env.sh
      - name: Test with docker-compose stack
        run: |
          docker-compose --env-file ./app/.env up -d --remove-orphans
          docker exec go_container go test -cover -v ./...