name: golang-ci

on:
  push:
    branches:
      - develop # mainの仮のdevelopに指定しておく
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test code
      run: go test -v ./...
      working-directory: ./app

